spring:
    application:
      name: locomotive
    data-source:
      url: jdbc:h2:mem:dev
      driver-class-name: org.h2.Driver
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create

security:
  basic:
    enabled: false
server:
    port: 8080